spring:
  mail:
    #smtp服务主机  qq邮箱则为smtp.qq.com
    host: smtp.139.com
    #服务协议
    protocol: smtp
    # 编码集
    default-encoding: UTF-8
    #发送邮件的账户
    username: 13600813851@139.com
    #授权码
    password: xxxxxxxxx
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
